
.incorporate-templates-commit:
  variables:
    FDO_DISTRIBUTION_TAG: "${HWC_TAG}--${CI_TEMPLATES_COMMIT}"

.container:
  stage: container
  extends:
    - .incorporate-templates-commit
  variables:
    FDO_REPO_SUFFIX: $CI_JOB_NAME
    # no need to pull the whole repo to build the container image
    GIT_STRATEGY: none

debian/x86_64_cuttlefish:
  extends:
    - .fdo.container-build@debian
    - .container
  timeout: 8h
  variables:
    FDO_DISTRIBUTION_VERSION: "trixie-slim"
    FDO_DISTRIBUTION_EXEC: 'bash .ci/container/debian/x86_64_cuttlefish.sh'
    HWC_TAG: $DEBIAN_CUTTLEFISH_TAG
  after_script:
    - cp "/cache/${CI_PROJECT_PATH}/cuttlefish.log.txt.gz" "${CI_PROJECT_DIR}/"
    - cp "/cache/${CI_PROJECT_PATH}/${CUTTLEFISH_TARBALL}" "${CI_PROJECT_DIR}/"
  artifacts:
    when: on_failure
    paths:
      - "${CI_PROJECT_DIR}/cuttlefish.log.txt.gz"
      - "${CI_PROJECT_DIR}/${CUTTLEFISH_TARBALL}"
    expire_in: 1 week

.ubuntu/x86_64_hwc:
  extends:
    - .fdo.container-build@ubuntu
    - .container

ubuntu/x86_64_aospless:
  extends:
    - .ubuntu/x86_64_hwc
  timeout: 2h
  variables:
    FDO_DISTRIBUTION_VERSION: "24.04"
    FDO_DISTRIBUTION_EXEC: 'bash .ci/container/ubuntu/x86_64_aospless.sh'
    HWC_TAG: $UBUNTU_AOSPLESS_TAG

ubuntu/x86_64_android_binaries:
  extends:
    - .ubuntu/x86_64_hwc
  timeout: 2h
  variables:
    FDO_DISTRIBUTION_VERSION: "24.04"
    FDO_DISTRIBUTION_EXEC: 'bash .ci/container/ubuntu/x86_64_android_binaries.sh'
    HWC_TAG: $UBUNTU_ANDROID_BINARIES_TAG

ubuntu/x86_64_android_tools:
  extends:
    - .ubuntu/x86_64_hwc
  timeout: 2h
  variables:
    ANDROID_VERSION: 17
    ANDROID_CTS_MODULES: >-
      CtsGraphicsTestCases
      CtsDisplayTestCases
    FDO_DISTRIBUTION_VERSION: "24.04"
    FDO_DISTRIBUTION_EXEC: 'bash .ci/container/ubuntu/x86_64_android_tools.sh'
    HWC_TAG: $UBUNTU_ANDROID_TOOLS_TAG

ubuntu/x86_64_android:
  extends:
    - .ubuntu/x86_64_hwc
  variables:
    FDO_DISTRIBUTION_VERSION: "24.04"
    FDO_DISTRIBUTION_EXEC: 'bash .ci/container/ubuntu/x86_64_android.sh'
    HWC_TAG: $UBUNTU_ANDROID_TAG
  needs:
  - job: debian/x86_64_cuttlefish
  - job: ubuntu/x86_64_android_binaries
  - job: ubuntu/x86_64_android_tools

.set-image:
  extends:
    - .incorporate-templates-commit
  image: "$CI_REGISTRY_IMAGE/${HWC_IMAGE}:${FDO_DISTRIBUTION_TAG}"

.use-ubuntu/x86_64_aospless:
  extends:
    - .fdo.container-build@ubuntu
    - .set-image
  variables:
    HWC_IMAGE: $UBUNTU_AOSPLESS_IMAGE
    HWC_TAG: $UBUNTU_AOSPLESS_TAG
  needs:
    - job: ubuntu/x86_64_aospless

.use-ubuntu/x86_64_android:
  extends:
    - .fdo.container-build@ubuntu
    - .set-image
  variables:
    HWC_IMAGE: $UBUNTU_ANDROID_IMAGE
    HWC_TAG: $UBUNTU_ANDROID_TAG
  needs:
    - job: ubuntu/x86_64_android
